/* STEX2 e-Kokurikulum — functional Supabase client */
(() => {
  const C = window.STEX2_CONFIG || {};
  const configured = C.SUPABASE_URL && !C.SUPABASE_URL.includes('PASTE_') && C.SUPABASE_KEY && !C.SUPABASE_KEY.includes('PASTE_');
  const sb = configured ? window.supabase.createClient(C.SUPABASE_URL, C.SUPABASE_KEY, {auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}}) : null;
  const state = { user:null, view:'dashboard', master:'murid', units:[], meetings:[], opr:[], calendar:[], houses:[], achievements:[], students:[], teachers:[], deferredPrompt:null };
  const $ = s => document.querySelector(s); const $$ = s => [...document.querySelectorAll(s)];
  const esc = v => String(v ?? '').replace(/[&<>'"]/g, m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[m]));
  const fmtDate = v => v ? new Date(v+'T00:00:00').toLocaleDateString('ms-MY',{day:'2-digit',month:'short',year:'numeric'}) : '-';
  const toast = (msg, error=false) => { const el=$('#toast'); el.textContent=msg; el.className='toast show'+(error?' error':''); setTimeout(()=>el.className='toast',2600); };
  const showModal = html => { $('#modalContent').innerHTML=html; $('#modal').showModal(); };
  const closeModal = () => $('#modal').close();
  async function q(table, opts={}) { if(!sb) return []; let x=sb.from(table).select(opts.select||'*'); if(opts.eq) Object.entries(opts.eq).forEach(([k,v])=>x=x.eq(k,v)); if(opts.order) x=x.order(opts.order,{ascending:opts.ascending!==false}); if(opts.limit) x=x.limit(opts.limit); const {data,error}=await x; if(error) throw error; return data||[]; }
  async function insert(table,payload){if(!sb)throw new Error('Supabase belum dikonfigurasi.'); const {data,error}=await sb.from(table).insert(payload).select(); if(error)throw error; return data;}
  async function update(table,id,payload){const {data,error}=await sb.from(table).update(payload).eq('id',id).select();if(error)throw error;return data;}
  async function remove(table,id){const {error}=await sb.from(table).delete().eq('id',id);if(error)throw error;}
  const table = (headers, rows) => `<table class="data-table"><thead><tr>${headers.map(h=>`<th>${h}</th>`).join('')}</tr></thead><tbody>${rows.length?rows.join(''):`<tr><td colspan="${headers.length}"><div class="no-data">Tiada rekod.</div></td></tr>`}</tbody></table>`;
  const optionList=(arr,valKey,labelKey,selected='')=>arr.map(x=>`<option value="${esc(x[valKey])}" ${String(x[valKey])===String(selected)?'selected':''}>${esc(x[labelKey])}</option>`).join('');

  async function init(){
    bindUI();
    if(!configured){ showAuth(false); toast('Sila isi config.js dengan URL dan publishable/anon key Supabase.', true); return; }
    const {data:{session}}=await sb.auth.getSession();
    session ? enter(session.user) : showAuth(true);
    sb.auth.onAuthStateChange((_e,s)=>{ if(s) enter(s.user); else showAuth(true); });
  }
  function showAuth(){ $('#authScreen').classList.remove('hidden'); $('#appShell').classList.add('hidden'); }
  async function enter(user){ state.user=user; $('#authScreen').classList.add('hidden'); $('#appShell').classList.remove('hidden'); $('#userEmail').textContent=user.email||'Guru'; await loadAll(); renderDashboard(); }
  async function loadAll(){
    try{
      [state.units,state.meetings,state.opr,state.calendar,state.houses,state.achievements,state.students,state.teachers] = await Promise.all([
        q('unit_counts',{order:'name'}),q('meetings',{order:'meeting_date',ascending:false}),q('opr',{order:'created_at',ascending:false}),q('calendar_events',{order:'event_date'}),q('houses_counts',{order:'name'}),q('achievements',{order:'created_at',ascending:false}),q('students',{order:'name'}),q('teachers',{order:'name'})
      ]);
      state.units.forEach(u=>{u.type_label=u.unit_type});
    }catch(e){ console.error(e); toast(e.message||'Gagal memuat data.',true); }
  }
  function bindUI(){
    $('#loginForm').addEventListener('submit', async e=>{e.preventDefault(); if(!sb)return toast('Supabase belum dikonfigurasi.',true); const email=$('#loginEmail').value.trim(), password=$('#loginPassword').value; const {error}=await sb.auth.signInWithPassword({email,password}); if(error)toast(error.message,true);});
    $('#logoutBtn').addEventListener('click',()=>sb?.auth.signOut());
    $('#menuToggle').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
    $$('.nav-item').forEach(b=>b.addEventListener('click',()=>go(b.dataset.view)));
    $$('[data-go]').forEach(b=>b.addEventListener('click',()=>go(b.dataset.go)));
    $('#installBtn').addEventListener('click',()=>installPWA());
    $('#addCalendarBtn').addEventListener('click',calendarForm); $('#addUnitBtn').addEventListener('click',unitForm); $('#newOprBtn').addEventListener('click',oprForm); $('#newMeetingBtn').addEventListener('click',meetingForm); $('#addHouseBtn').addEventListener('click',houseForm); $('#addAchievementBtn').addEventListener('click',achievementForm); $('#refreshAnalysisBtn').addEventListener('click',async()=>{await loadAll();renderAnalysis();toast('Analisis dikemas kini.');});
    $('#unitTypeFilter').addEventListener('change',renderUnits); $('#unitSearch').addEventListener('input',renderUnits);
    $$('.tab').forEach(t=>t.addEventListener('click',()=>{ $$('.tab').forEach(x=>x.classList.remove('active'));t.classList.add('active');state.master=t.dataset.master;renderMaster();}));
    window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();state.deferredPrompt=e;$('#installBtn').style.display='inline-flex';});
    if(!state.deferredPrompt) $('#installBtn').style.display='none';
  }
  function go(view){ state.view=view; $$('.view').forEach(x=>x.classList.remove('active-view')); $(`#view-${view}`).classList.add('active-view'); $$('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.view===view)); const titles={dashboard:['Dashboard','Dashboard Kokurikulum'],takwin:['Takwim','Takwim Kokurikulum'],units:['Pengurusan Unit','Unit Kokurikulum'],opr:['Jana OPR','One Page Report'],attendance:['Kehadiran','Kehadiran Perjumpaan'],houses:['Rumah Sukan','Rumah Sukan'],achievements:['Pencapaian Murid','Rekod Pencapaian Murid'],master:['Master Data','Data Murid & Guru'],analysis:['Analisis','Analisis Kokurikulum']}; $('#viewTitle').textContent=titles[view][0];$('#pageTitle').textContent=titles[view][1]; $('#sidebar').classList.remove('open'); if(view==='dashboard')renderDashboard(); if(view==='takwin')renderCalendar(); if(view==='units')renderUnits(); if(view==='opr')renderOpr(); if(view==='attendance')renderMeetings(); if(view==='houses')renderHouses(); if(view==='achievements')renderAchievements(); if(view==='master')renderMaster(); if(view==='analysis')renderAnalysis(); }

  function renderDashboard(){
    const completed=new Set(state.opr.map(x=>x.meeting_id).filter(Boolean));
    const pending=state.meetings.filter(m=>!completed.has(m.id)).slice(0,5);
    $('#dashboardStats').innerHTML=[['Unit aktif',state.units.length],['Murid',state.students.length],['Guru',state.teachers.length],['OPR dihantar',state.opr.length]].map(([a,b])=>`<div class="stat"><small>${a}</small><strong>${b}</strong></div>`).join('');
    $('#pendingOpr').innerHTML=pending.length?pending.map(m=>{const u=state.units.find(x=>x.id===m.unit_id);return `<div class="list-item"><div><strong>${esc(u?.name||'Unit')}</strong><small>${fmtDate(m.meeting_date)} · Perjumpaan ${m.meeting_no||'-'}</small></div><span class="pill danger">Belum OPR</span></div>`}).join(''):`<div class="no-data">Tiada perjumpaan tertunggak.</div>`;
    const upcoming=state.calendar.filter(x=>new Date(x.event_date+'T23:59:59')>=new Date()).slice(0,5); $('#upcomingCalendar').innerHTML=upcoming.length?upcoming.map(x=>`<div class="list-item"><div><strong>${esc(x.title)}</strong><small>${fmtDate(x.event_date)} · ${esc(x.location||'')}</small></div><span class="pill">${esc(x.category||'Aktiviti')}</span></div>`).join(''):`<div class="no-data">Tiada aktiviti akan datang.</div>`;
  }
  function renderCalendar(){ $('#calendarList').innerHTML=table(['Tarikh','Aktiviti','Kategori','Tempat','Tindakan'],state.calendar.map(x=>`<tr><td>${fmtDate(x.event_date)}</td><td><strong>${esc(x.title)}</strong><br>${esc(x.description||'')}</td><td><span class="pill">${esc(x.category||'-')}</span></td><td>${esc(x.location||'-')}</td><td><button class="btn ghost" onclick="window.delCalendar('${x.id}')">Padam</button></td></tr>`)); }
  window.delCalendar=async id=>{if(!confirm('Padam aktiviti ini?'))return;try{await remove('calendar_events',id);await loadAll();renderCalendar();renderDashboard();toast('Aktiviti dipadam.')}catch(e){toast(e.message,true)}};
  async function calendarForm(){showModal(`<div class="modal"><h3>Tambah Aktiviti Takwim</h3><form id="f" class="form-grid"><label>Tarikh<input name="event_date" type="date" required></label><label>Kategori<select name="category"><option>Perjumpaan Unit</option><option>Program Sekolah</option><option>Kejohanan</option><option>Pertandingan</option><option>Lain-lain</option></select></label><label class="full">Nama aktiviti<input name="title" required></label><label>Tempat<input name="location"></label><label>Catatan<textarea name="description" rows="3"></textarea></label><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`); $('#f').onsubmit=async e=>{e.preventDefault();try{await insert('calendar_events',Object.fromEntries(new FormData(e)));closeModal();await loadAll();renderCalendar();renderDashboard();toast('Aktiviti disimpan.')}catch(err){toast(err.message,true)}}}

  function renderUnits(){ const type=$('#unitTypeFilter').value.toLowerCase(), term=$('#unitSearch').value.toLowerCase(); const list=state.units.filter(u=>(!type||u.unit_type?.toLowerCase()===type)&&(!term||u.name.toLowerCase().includes(term))); $('#unitsGrid').innerHTML=list.length?list.map(u=>{const gm=u.guru_count||0,sm=u.member_count||0;return `<article class="unit-card"><div class="unit-type">${esc(u.unit_type)}</div><h4>${esc(u.name)}</h4><p class="muted">${esc(u.description||'Tiada penerangan')}</p><div class="unit-meta"><span class="pill">${sm} murid</span><span class="pill">${gm} guru</span></div><div class="unit-actions"><button class="btn secondary" onclick="window.unitEdit('${u.id}')">Edit</button><button class="btn ghost" onclick="window.unitDelete('${u.id}')">Padam</button></div></article>`}).join(''):`<div class="card no-data" style="grid-column:1/-1">Belum ada unit. Tambahkan unit pertama anda.</div>`; }
  async function unitForm(id=null){const old=id?state.units.find(x=>x.id===id):{};showModal(`<div class="modal"><h3>${id?'Edit Unit':'Tambah Unit Kokurikulum'}</h3><form id="f" class="form-grid"><label>Nama unit<input name="name" required value="${esc(old.name||'')}"></label><label>Kategori<select name="unit_type"><option ${old.unit_type==='Unit Uniform'?'selected':''}>Unit Uniform</option><option ${old.unit_type==='Kelab & Persatuan'?'selected':''}>Kelab & Persatuan</option><option ${old.unit_type==='Sukan & Permainan'?'selected':''}>Sukan & Permainan</option></select></label><label class="full">Penerangan<textarea name="description" rows="3">${esc(old.description||'')}</textarea></label><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`); $('#f').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e)); if(id)await update('units',id,p);else await insert('units',p);closeModal();await loadAll();renderUnits();renderDashboard();toast(id?'Unit dikemas kini.':'Unit ditambah.')}catch(err){toast(err.message,true)}}}
  window.unitEdit=unitForm;window.unitDelete=async id=>{if(!confirm('Padam unit ini? Data berkaitan mungkin turut bergantung pada unit.'))return;try{await remove('units',id);await loadAll();renderUnits();renderDashboard();toast('Unit dipadam.')}catch(e){toast(e.message,true)}};

  function renderOpr(){ $('#oprList').innerHTML=table(['Tarikh','Unit','Perjumpaan','Tajuk Aktiviti','Status','Tindakan'],state.opr.map(x=>{const u=state.units.find(a=>a.id===x.unit_id);return `<tr><td>${fmtDate(x.activity_date)}</td><td>${esc(u?.name||'-')}</td><td>${x.meeting_no||'-'}</td><td>${esc(x.activity_title||'-')}</td><td><span class="pill success">Dihantar</span></td><td><button class="btn secondary" onclick="window.oprPdf('${x.id}')">PDF</button></td></tr>`}).join('')); }
  async function oprForm(){showModal(`<div class="modal"><h3>Jana One Page Report</h3><form id="f" class="form-grid"><label>Perjumpaan<select name="meeting_id" required><option value="">Pilih perjumpaan</option>${state.meetings.map(m=>{const u=state.units.find(x=>x.id===m.unit_id);return `<option value="${m.id}">${fmtDate(m.meeting_date)} · ${esc(u?.name||'Unit')} · #${m.meeting_no||'-'}</option>`}).join('')}</select></label><label>Unit<select id="oprUnit" name="unit_id" required>${optionList(state.units,'id','name')}</select></label><label>Tarikh<input name="activity_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>Bil. Perjumpaan<input name="meeting_no" type="number" min="1" value="1"></label><label>Tajuk aktiviti<input name="activity_title" required></label><label class="full">Objektif<textarea name="objective" rows="3"></textarea></label><label class="full">Aktiviti / perjalanan program<textarea name="activity_description" rows="5"></textarea></label><label>Bilangan hadir<input name="attendance_count" type="number" min="0"></label><label>Guru penasihat<input name="teacher_in_charge"></label><div class="full"><label>Gambar aktiviti (URL, satu setiap baris)<textarea name="photo_urls" rows="3" placeholder="https://..."></textarea></label></div><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan & Jana PDF</button></div></form></div>`); $('#f').querySelector('[name=meeting_id]').addEventListener('change',e=>{const m=state.meetings.find(x=>x.id===e.target.value);if(!m)return;$('#f [name=unit_id]').value=m.unit_id;$('#f [name=activity_date]').value=m.meeting_date;$('#f [name=meeting_no]').value=m.meeting_no||1;}); $('#f').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e));p.created_by=state.user?.id;const rows=await insert('opr',p);closeModal();await loadAll();renderOpr();renderDashboard();toast('OPR disimpan.'); if(rows?.[0])await downloadOprPdf(rows[0].id);}catch(err){toast(err.message,true)}}}
  async function downloadOprPdf(id){const x=state.opr.find(a=>a.id===id);if(!x)return;const u=state.units.find(a=>a.id===x.unit_id);const fotos=(x.photo_urls||'').split('\n').map(s=>s.trim()).filter(Boolean);const paper=document.createElement('div');paper.className='report-paper';paper.innerHTML=`<div class="report-head"><div><h1>SMK TAMAN SCIENTEX 2</h1><p>JEA1102 · e-Kokurikulum — ONE PAGE REPORT</p></div><div class="report-logo">S2</div></div><div class="report-section"><h2>MAKLUMAT AKTIVITI</h2><table class="report-table"><tr><td><b>Unit</b></td><td>${esc(u?.name||'-')}</td><td><b>Tarikh</b></td><td>${fmtDate(x.activity_date)}</td></tr><tr><td><b>Perjumpaan</b></td><td>${esc(x.meeting_no||'-')}</td><td><b>Hadir</b></td><td>${esc(x.attendance_count||0)}</td></tr><tr><td><b>Tajuk</b></td><td colspan="3">${esc(x.activity_title||'-')}</td></tr></table></div><div class="report-section"><h2>OBJEKTIF</h2><p style="font-size:11px">${esc(x.objective||'-')}</p></div><div class="report-section"><h2>AKTIVITI / PERJALANAN</h2><p style="font-size:11px;line-height:1.5">${esc(x.activity_description||'-')}</p></div><div class="report-section"><h2>DOKUMENTASI GAMBAR</h2><div class="photo-grid">${[0,1,2,3].map(i=>fotos[i]?`<div class="photo-slot"><img src="${esc(fotos[i])}" style="max-width:100%;max-height:170px" onerror="this.parentNode.textContent='Gambar tidak dapat dimuatkan'"></div>`:`<div class="photo-slot">Gambar ${i+1}</div>`).join('')}</div></div><div class="report-footer">Disediakan oleh: ${esc(x.teacher_in_charge||'Guru Penasihat')} · Dijana melalui STEX2 e-Kokurikulum</div>`;document.body.appendChild(paper);await html2pdf().set({margin:0,filename:`OPR-${(u?.name||'unit').replace(/[^a-z0-9]+/gi,'-')}-${x.activity_date}.pdf`,image:{type:'jpeg',quality:.95},html2canvas:{scale:2,useCORS:true},jsPDF:{unit:'pt',format:'a4',orientation:'portrait'}}).from(paper).save();paper.remove();}
  window.oprPdf=downloadOprPdf;

  function renderMeetings(){ $('#meetingList').innerHTML=table(['Tarikh','Unit','No.','Tempat','OPR','Tindakan'],state.meetings.map(m=>{const u=state.units.find(x=>x.id===m.unit_id),has=state.opr.some(o=>o.meeting_id===m.id);return `<tr><td>${fmtDate(m.meeting_date)}</td><td>${esc(u?.name||'-')}</td><td>${m.meeting_no||'-'}</td><td>${esc(m.location||'-')}</td><td>${has?'<span class="pill success">Dihantar</span>':'<span class="pill danger">Belum</span>'}</td><td><button class="btn ghost" onclick="window.delMeeting('${m.id}')">Padam</button></td></tr>`}).join('')); }
  async function meetingForm(){showModal(`<div class="modal"><h3>Tambah Perjumpaan</h3><form id="f" class="form-grid"><label>Unit<select name="unit_id" required>${optionList(state.units,'id','name')}</select></label><label>Tarikh<input name="meeting_date" type="date" required value="${new Date().toISOString().slice(0,10)}"></label><label>No. perjumpaan<input name="meeting_no" type="number" min="1" value="1"></label><label>Tempat<input name="location"></label><label class="full">Aktiviti ringkas<textarea name="activity_description" rows="3"></textarea></label><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`); $('#f').onsubmit=async e=>{e.preventDefault();try{await insert('meetings',Object.fromEntries(new FormData(e)));closeModal();await loadAll();renderMeetings();renderDashboard();toast('Perjumpaan disimpan.')}catch(err){toast(err.message,true)}}}
  window.delMeeting=async id=>{if(!confirm('Padam perjumpaan?'))return;try{await remove('meetings',id);await loadAll();renderMeetings();renderDashboard();toast('Perjumpaan dipadam.')}catch(e){toast(e.message,true)}};

  function renderHouses(){ $('#housesGrid').innerHTML=state.houses.length?state.houses.map(h=>`<article class="unit-card"><div class="unit-type">RUMAH SUKAN</div><h4>${esc(h.name)}</h4><p class="muted">Warna: ${esc(h.color||'-')}</p><div class="unit-meta"><span class="pill">${h.member_count||0} murid</span><span class="pill">${h.teacher_count||0} guru</span></div><div class="unit-actions"><button class="btn secondary" onclick="window.houseEdit('${h.id}')">Edit</button></div></article>`).join(''):`<div class="card no-data" style="grid-column:1/-1">Belum ada rumah sukan.</div>`;}
  async function houseForm(id=null){const old=id?state.houses.find(x=>x.id===id):{};showModal(`<div class="modal"><h3>${id?'Edit':'Tambah'} Rumah Sukan</h3><form id="f" class="form-grid"><label>Nama rumah<input name="name" required value="${esc(old.name||'')}"></label><label>Warna<input name="color" value="${esc(old.color||'')}"></label><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`);$('#f').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e));if(id)await update('houses',id,p);else await insert('houses',p);closeModal();await loadAll();renderHouses();toast('Rumah sukan disimpan.')}catch(err){toast(err.message,true)}}}window.houseEdit=houseForm;

  function renderAchievements(){ $('#achievementList').innerHTML=table(['Murid','Aktiviti','Peringkat','Pencapaian','Tahun','Tindakan'],state.achievements.map(a=>`<tr><td>${esc(a.student_name||'-')}</td><td>${esc(a.activity_name||'-')}</td><td>${esc(a.level||'-')}</td><td>${esc(a.achievement||'-')}</td><td>${a.year||'-'}</td><td><button class="btn ghost" onclick="window.delAchievement('${a.id}')">Padam</button></td></tr>`).join('')); }
  async function achievementForm(){showModal(`<div class="modal"><h3>Rekod Pencapaian Murid</h3><form id="f" class="form-grid"><label>Nama murid<input name="student_name" required placeholder="Nama penuh"></label><label>Tahun<input name="year" type="number" value="${new Date().getFullYear()}"></label><label>Aktiviti / pertandingan<input name="activity_name" required></label><label>Peringkat<select name="level"><option>Sekolah</option><option>Daerah</option><option>Negeri</option><option>Kebangsaan</option><option>Antarabangsa</option></select></label><label class="full">Pencapaian / anugerah<input name="achievement"></label><label class="full">Catatan<textarea name="notes" rows="3"></textarea></label><div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`);$('#f').onsubmit=async e=>{e.preventDefault();try{await insert('achievements',Object.fromEntries(new FormData(e)));closeModal();await loadAll();renderAchievements();toast('Pencapaian disimpan.')}catch(err){toast(err.message,true)}}}window.delAchievement=async id=>{if(!confirm('Padam rekod?'))return;try{await remove('achievements',id);await loadAll();renderAchievements();toast('Rekod dipadam.')}catch(e){toast(e.message,true)}};

  function renderMaster(){const isS=state.master==='murid',arr=isS?state.students:state.teachers;$('#masterList').innerHTML=`<div style="display:flex;justify-content:flex-end;margin-bottom:12px"><button class="btn primary" onclick="window.masterAdd('${state.master}')">+ Tambah ${isS?'Murid':'Guru'}</button></div>`+table(isS?['Nama','No. MyKad / ID','Tingkatan','Kelas','Tindakan']:['Nama','Email','Jawatan','Tindakan'],arr.map(x=>`<tr><td><strong>${esc(x.name)}</strong></td><td>${esc(isS?x.student_no:x.email||'-')}</td><td>${esc(isS?x.form_level:x.position||'-')}</td><td>${esc(isS?x.class_name:'')}</td><td><button class="btn secondary" onclick="window.masterEdit('${state.master}','${x.id}')">Edit</button> <button class="btn ghost" onclick="window.masterDelete('${state.master}','${x.id}')">Padam</button></td></tr>`).join(''));}
  async function masterAdd(kind,id=null){const isS=kind==='murid',old=id?(isS?state.students:state.teachers).find(x=>x.id===id):{};showModal(`<div class="modal"><h3>${id?'Edit':'Tambah'} ${isS?'Murid':'Guru'}</h3><form id="f" class="form-grid"><label>Nama penuh<input name="name" required value="${esc(old.name||'')}"></label>${isS?`<label>No. murid / ID<input name="student_no" value="${esc(old.student_no||'')}"></label><label>Tingkatan<input name="form_level" value="${esc(old.form_level||'')}"></label><label>Kelas<input name="class_name" value="${esc(old.class_name||'')}"></label>`:`<label>Email<input name="email" type="email" value="${esc(old.email||'')}"></label><label>Jawatan<input name="position" value="${esc(old.position||'')}"></label><label>No. telefon<input name="phone" value="${esc(old.phone||'')}"></label>`}<div class="full form-actions"><button type="button" class="btn ghost" onclick="window.closeM()">Batal</button><button class="btn primary">Simpan</button></div></form></div>`);$('#f').onsubmit=async e=>{e.preventDefault();try{const p=Object.fromEntries(new FormData(e));if(id)await update(isS?'students':'teachers',id,p);else await insert(isS?'students':'teachers',p);closeModal();await loadAll();renderMaster();renderDashboard();toast('Data disimpan.')}catch(err){toast(err.message,true)}}}
  window.masterAdd=masterAdd;window.masterEdit=masterAdd;window.masterDelete=async(kind,id)=>{if(!confirm('Padam rekod ini?'))return;try{await remove(kind==='murid'?'students':'teachers',id);await loadAll();renderMaster();renderDashboard();toast('Rekod dipadam.')}catch(e){toast(e.message,true)}};

  function renderAnalysis(){const total=state.meetings.length,submitted=state.opr.length,pct=total?Math.round(submitted/total*100):0;const cats=['Unit Uniform','Kelab & Persatuan','Sukan & Permainan'].map(cat=>{const n=state.units.filter(u=>u.unit_type===cat).length;return `<div class="bar"><span>${cat}</span><div class="bar-track"><div class="bar-fill" style="width:${Math.min(n*15,100)}%"></div></div><b>${n}</b></div>`}).join('');$('#analysisBody').innerHTML=`<div class="analysis-box"><h4>Laporan OPR</h4><div class="analysis-number">${pct}%</div><p class="muted">${submitted} daripada ${total} perjumpaan mempunyai OPR.</p></div><div class="analysis-box"><h4>Komposisi Unit</h4><div class="analysis-bars">${cats}</div></div><div class="analysis-box"><h4>Data Induk</h4><p><b>${state.students.length}</b> murid</p><p><b>${state.teachers.length}</b> guru</p><p><b>${state.houses.length}</b> rumah sukan</p><p><b>${state.achievements.length}</b> rekod pencapaian</p></div>`;}
  function installPWA(){if(state.deferredPrompt){state.deferredPrompt.prompt();state.deferredPrompt=null;$('#installBtn').style.display='none';}else toast('Pada iPhone/iPad: buka Safari → Share → Add to Home Screen. Pada Android/Chrome: menu ⋮ → Install app / Add to Home Screen.');}
  window.closeM=closeModal;
  init();
})();
